### ISSUE TITLE
Consider using sha256sum over shasum for EL6 support

### ISSUE THREAD

**Issue by kakawait** [silpion/ansible-java#12]
`shasum` is not built-in EL6 but `sha256sum` is. And ubuntu / debian should include `sha256sum` by default.

**Comment by spul** [comment]
I'll add this to my TODO list again after a lot of work has been done. Sorry to keep you waiting so long.

**Comment by spul** [comment]
Hi,

I've just released a new version 1.1.0 and uploaded to galaxy. This allows to configure shasum command to use and tries to guess local_action: command shasum over a list of possible places where to look (common *nix like behaviour) if configuration is left empty.
