### ISSUE TITLE
Download Oracle Java redis package fails

### ISSUE THREAD

**Issue by victorfranz** [silpion/ansible-java#17]
Hi,

I'm trying to run it but I'm getting the message:
TASK: [java | Download Oracle Java redis package] ***************************** 
<127.0.0.1> REMOTE_MODULE command curl --location --insecure --remote-name --cookie oraclelicense=accept-securebackup-cookie --cookie-jar /tmp/jdk-7u51-linux-x64.tar.gz.cookie http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz chdir=/root/.ansible/assets creates=/root/.ansible/assets/jdk-7u51-linux-x64.tar.gz
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1439525431.67-132428685474733 && echo $HOME/.ansible/tmp/ansible-tmp-1439525431.67-132428685474733']
<127.0.0.1> PUT /tmp/tmpWiOpaq TO /root/.ansible/tmp/ansible-tmp-1439525431.67-132428685474733/command
<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jfuovnxoymvuuqczbmqmeinsojbspxlz] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jfuovnxoymvuuqczbmqmeinsojbspxlz; LANG=C LC_CTYPE=C /usr/bin/python /root/.ansible/tmp/ansible-tmp-1439525431.67-132428685474733/command; rm -rf /root/.ansible/tmp/ansible-tmp-1439525431.67-132428685474733/ >/dev/null 2>&1'"'"''
failed: [liferay -> 127.0.0.1] => {"cmd": "curl --location --insecure --remote-name --cookie oraclelicense=accept-securebackup-cookie --cookie-jar /tmp/jdk-7u51-linux-x64.tar.gz.cookie http://download.oracle.com/otn-pub/java/jdk/7u51-b13/jdk-7u51-linux-x64.tar.gz", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

Am I missing something?

**Comment by spul** [comment]
Looks like you don't have ``curl`` available on your local workstation.

**Comment by victorfranz** [comment]
Hi,

It is available, I tried with the full path too (/usr/bin/curl) but had the same error.

**Comment by victorfranz** [comment]
I just updated my Ubuntu installation, did checkout again and re run all and it worked.
