### ISSUE TITLE
having some dictionary issues with java....

### ISSUE THREAD

**Issue by rvanderwerf** [silpion/ansible-java#18]
Thanks for making these playbooks, I really hope I can get all of this working as I'm tired of ubuntu having such old versions of Tomcat which I can't get to pass PCI scans. Anyhow I am stuck at this point (step 33 or so) in trying to install the tomcat services. I'm not sure I have the facts stuff set right for java. I already have java installed through my own playbook for jdk 8. I think it's having an issue installing it again but I'm not sure. I've got my own playbook current that calls the groover.tomcat role from inside it after it install the JDK. 

<10.0.2.248> ESTABLISH CONNECTION FOR USER: ubuntu
<10.0.2.248> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rvanderwerf/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o IdentityFile="/home/rvanderwerf/.ssh/something.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 10.0.2.248 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957 && echo $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957'
fatal: [10.0.2.248] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'java'", 'failed': True}
fatal: [10.0.2.248] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'java'", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

10.0.2.248                 : ok=33   changed=1    unreachable=1    failed=0   
localhost                  : ok=7    changed=0    unreachable=0    failed=0
--------

this is what I have in my local /etc/ansible/facts.d/java.fact - I'm not sure if this is right as I don't see examples:
ansible_local.java.general.java_home=/usr/lib/jvm/java-8-oracle/jre/bin/java

Any ideas what I might be doing wrong?

**Comment by spul** [comment]
Hi,

you need to create the facts for java like this:

``cat /etc/ansible/facts.d/java.fact``



``
[general]
java_home = /path/to/your/jvm/home/directory
``

This results in a local fact named ``ansible_local.java.general.java_home``.

**Comment by rvanderwerf** [comment]
Thanks for the response! I'm still a little green with Ansible. I have this on my local system:
 # cat /etc/ansible/facts.d/java.fact 
[general]
java_home=/usr/lib/jvm/java-8-oracle/

which is valid, also on my remote host I am installing, that path is valid too. Unfortunately I still get the same error :(

**Comment by spul** [comment]
Hi,

please review/provide the following ad-hoc command targeted at the managed node:

```
ansible <MANAGED_NODE> -m setup -a filter=ansible_local
```

This will show you local facts available on the remote node in JSON representation. Which task exactly is failing by the way?

**Comment by rvanderwerf** [comment]
sorry  here is the task which I forgot to put on top of the error msg. I'll run the command to grab the ad-hoc info thx:
 ________________________________________________
< TASK: groover.tomcat | Install tomcat services >
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
<10.0.2.248> ESTABLISH CONNECTION FOR USER: ubuntu
<10.0.2.248> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/rvanderwerf/.ansible/cp/ansible-ssh-%h-%p-%r" -o Port=22 -o IdentityFile="/home/rvanderwerf/.ssh/something.pem" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 10.0.2.248 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957 && echo $HOME/.ansible/tmp/ansible-tmp-1440452938.08-106570046307957'
fatal: [10.0.2.248] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'java'", 'failed': True}
fatal: [10.0.2.248] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'dict object' has no attribute 'java'", 'failed': True}]}

FATAL: all hosts have already failed -- aborting

**Comment by rvanderwerf** [comment]
here's the output: 

10.0.2.248 | success >> {
    "ansible_facts": {
        "ansible_local": {
            "util": {
                "general": {
                    "package_state": "installed", 
                    "persistent_data_path": "/usr/local/src/ansible/data", 
                    "role_version": "1.0.0", 
                    "template_use_cow": "True"
                }, 
                "init": {
                    "system": "upstart"
                }, 
                "modules": {
                    "apt": {
                        "cache_valid_time": "3600"
                    }, 
                    "get_url": {
                        "timeout": "10"
                    }, 
                    "service": {
                        "allow_reload": "True", 
                        "allow_restart": "True", 
                        "manage": "True"
                    }
                }
            }
        }
    }, 
    "changed": false
}


it looks like the local fact from my box isn't getting to the managed node - I assume I'm not manually setting up a fact on the managed server correct?

**Comment by spul** [comment]
Yes, there's no java facts on the managed noded but they need to get there. ``Local`` facts do not have to do with your local system you're running ansible on. They are ``local`` to the system you are managing. So you'd need to deploy the java.fact file on the managed node to make the facts available for the tomcat role.

What happens is... Ansible generates Python code on your local workstation. It uploads the generated code to the managed node and finaly runs in on the managed node.
The template module used in the task which is failing for you is executed on the remote/managed node and tries to fill variables which need to be accessable on that remote/managed node but right now simply aren't.

Hope this explains a few things to you and hope you'll get this done quickly.

Note: You can ``template:`` or ``copy``: the file from your workstation to the managed node with ``pre_tasks`` in your play/playbook.

**Comment by rvanderwerf** [comment]
great I understand now thanks for your help!
