### ISSUE TITLE
Install failing on sha256sum check for supported java version

### ISSUE THREAD

**Issue by WeVaSoft** [silpion/ansible-java#20]
Just tried running this  role with one of the supported java versions as follows :
 
    - { role: ansible-java, java_oracle_distribution: jre, java_oracle_version: 7u80 }

and installation is failing on checksum verification with the following error message.

TASK: [ansible-java | Ensure downloaded archives are world readable] **********
ok: [127.0.0.1 -> 127.0.0.1] => (item=jre-7u80-linux-x64.tar.gz)
ok: [127.0.0.1 -> 127.0.0.1] => (item=UnlimitedJCEPolicyJDK7.zip)

TASK: [ansible-java | Verify Oracle Java redis package sha256sum] *************
failed: [127.0.0.1 -> 127.0.0.1] => {"changed": true, "cmd": ["/usr/bin/shasum", "--check", "--status", "--algorithm", "256", "/home/vagrant/.ansible/assets/java.sha256sum"], "delta": "0:00:00.355942", "end": "2015-12-13 17:29:32.934563", "rc": 1, "start": "2015-12-13 17:29:32.578621", "warnings": []}

FATAL: all hosts have already failed -- 
aborting

**Comment by WeVaSoft** [comment]
Running the shasum command on the downloaded jre-7u80-linux-x64.tar.gz file gave me a different value than the one in the  vars/versions/7u80.yml file.  
$ shasum -a 256 jre-7u80-linux-x64.tar.gz
4c01efd0d8e80bb6e2f324ec3408ce64f066d4506c7ec93a491f615a4523f4f3  jre-7u80-linux-x64.tar.gz

So, i changed the 7u80.yml file value to above, and install succeeded. 

Now i am wondering is the original value in 7u80.yml file wrong, or did i download a bad tar file?

**Comment by spul** [comment]
Hi,

this was a copy/paste issue I guess for the JRE distribution. I got that fixed right now and tagged a hotfix 1.5.1. Thanks for the catch/report!
