### ISSUE TITLE
Destination directory /etc/ansible/facts.d does not exist.

### ISSUE THREAD

**Issue by nmische** [silpion/ansible-java#21]
I get the following error when I try to use this role:

```
TASK: [groover.java | Install java facts] *************************************
failed: [localhost] => {"failed": true}
msg: Destination directory /etc/ansible/facts.d does not exist
```

It looks like this commit removed the `Install Ansible facts.d directory` task that ensured this directory was present: https://github.com/silpion/ansible-java/commit/3eeefef7971e5d1885b35c7cba28285eeb382294

**Comment by spul** [comment]
This should never be the case if [groover.util](https://github.com/silpion/ansible-util) ran at least once. util is in dependencies of java role and therefor I cannot consider this a bug/issue in the java role itself.

**Comment by nmische** [comment]
If `groover.util` needs to run this this should be done explicitly in the java role's `main.yml`. As it stands now the example playbook fails with this error.

**Comment by nmische** [comment]
Nevermind. I found that my `groover.util` was pinned to an older version. Upon retesting with the latest `groover.util` version all is working as expected.
