### ISSUE TITLE
Curl KeepAlive timeouts

### ISSUE THREAD

**Issue by kuza55** [silpion/ansible-java#23]
I don't know if this is worth dealing with in this playbook, but when I tried to use this to setup an AWS machine I got errors like this when downloading java packages:

curl: (18) transfer closed with 168704464 bytes remaining to read

This was solved pretty easily by adding --keepalive-time 2 to download.yml, but it did take a little bit of time to figure out this work around.

**Comment by spul** [comment]
Hi,

as we currently are updating all public roles for v2 I'll take this into account when updating the java role. I've some ideas on this as well and need to verify. Hope we'll be ready to release all roles with major version upgrade somewhere in next week.

**Comment by spul** [comment]
``--connect-timeout`` is now implemented with [2.0.1][1] release.

[1]: https://github.com/silpion/ansible-java/tree/2.0.1
