### ISSUE TITLE
Add java to path

### ISSUE THREAD

**Issue by Bedotech** [silpion/ansible-java#27]
what is the best way for add java installed available to path? in a ubuntu 14.04?

**Comment by spul** [comment]
java role deploys /etc/profile.d/java.sh, so ``. /etc/profile`` in an interactive shell should take care of have JAVA_HOME correctly, and sets ``PATH=${PATH}:${JAVA_HOME}/bin", so when running the role in vagrant, ``vagrant ssh -- which java`` should function properly out of the box.

Just did the following:

```
$ rake provision

...
PLAY RECAP *********************************************************************
ansiblejavatest            : ok=55   changed=17   unreachable=0    failed=0
```

```
$ vagrant ssh -- which java
/opt/java/oracle/jdk1.8.0_66/bin/java
```

**Comment by Bedotech** [comment]
Ok, but this work for www-data user? i have some some line in PHP that call Java but it doesn't work.

**Comment by spul** [comment]
That doesn't sound like a good idea at all, anyway what you can do with your playbook is using the local facts from java role and configure PHP with, e.g. with ``template`` or ``ini`` module. Use ``{{ ansible_local.java.general.java_home }}/bin/java`` for this.

**Comment by Bedotech** [comment]
yeah it isn't good idea at all, but i cant upgrade the code :cry: 

thanks for the reply.
