### ISSUE TITLE
Documentation shows two variable name for the same setting

### ISSUE THREAD

**Issue by robertomoutinho** [silpion/ansible-java#33]
Hi,

I've noticed that on the README file

On the "Synopsis" you mention:
    **oracle_java_version**
    **oracle_java_distribution**

On the "Role Variables" section:
    **java_oracle_distribution**
    **java_oracle_version**

Regards

**Comment by spul** [comment]
Yes, right. Nice catch. I've that fixed in next branch. Thank you!
