### ISSUE TITLE
Add support for server jre

### ISSUE THREAD

**Issue by idyedov** [silpion/ansible-java#5]
Please add support for server-jre

**Comment by spul** [comment]
Uh, totaly missed that. I'll add that to my TODOs.

**Comment by ludovicc** [comment]
Serve JRE is unfortunately not packaged for Debian or RedHat. This role could be a good start to install a server JRE. Even better, FPM (https://github.com/jordansissel/fpm) could be used to package the tar.gz provided by Oracle and transform it into a .deb or .rpm.

**Comment by spul** [comment]
Finaly got some time to address this. server-jre is now available when configuring ``java_oracle_distribution`` to ``srv`` with 1.4.0.
