### ISSUE TITLE
Wrong depedendency in meta/main.yml

### ISSUE THREAD

**Issue by mmannerm** [silpion/ansible-java#9]
dependencies:
  - { role: silpion.util }

groover.util is the one that is in galaxy

**Comment by kevinrivers** [comment]
You have to use the requirements.yml file to set it up properly.

- src: groover.util
  name: silpion.util

**Comment by spul** [comment]
All documented in README. Thanks for the interest in this role anyway :)

**Comment by repsah** [comment]
Sorry, I might be a newbie but without kevinrivers comment I wouldn't have understood how to set it up (and I read the README), I would include it in the README.
